"""
ZIA Web Category — Deep Analysis
------------------------------------
Analyzes custom URL categories for hygiene issues: duplicate URLs,
stale entries, single-use categories, cross-policy inconsistencies.

Reads url_cat.json for category data (not embedded).

PowerShell:
    pip install openpyxl python-docx
    python zia_webcategory_analysis.py url_filtering.json sslpol.json

Place url_cat.json in the same folder (generated by zia_category_extractor.py
or exported from the HAR conversion).

Output (in current directory):
    - ZIA_WebCategory_Analysis.xlsx
    - ZIA_WebCategory_Analysis.docx
"""

import json, sys, os
from collections import Counter, defaultdict

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl required. Install with: pip install openpyxl")
    sys.exit(1)

try:
    from docx import Document as DocxDocument
    from docx.shared import Pt
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False
    print("NOTE: python-docx not installed — Word doc skipped.")

BOLD = Font(name="Calibri", bold=True, size=11)
NORMAL = Font(name="Calibri", size=11)
TITLE = Font(name="Calibri", bold=True, size=14)
SUBTITLE = Font(name="Calibri", bold=True, size=12)
HEADER_FILL = PatternFill("solid", fgColor="404040")
HEADER_FONT = Font(name="Calibri", bold=True, size=11, color="FFFFFF")
LIGHT_RED = PatternFill("solid", fgColor="F2DCDB")
LIGHT_ORANGE = PatternFill("solid", fgColor="FDE9D9")
LIGHT_YELLOW = PatternFill("solid", fgColor="FFFFCC")
BDR = Border(left=Side(style="thin", color="AAAAAA"), right=Side(style="thin", color="AAAAAA"),
             top=Side(style="thin", color="AAAAAA"), bottom=Side(style="thin", color="AAAAAA"))

def hdr(ws, row, headers):
    for c, h in enumerate(headers, 1):
        cl = ws.cell(row=row, column=c, value=h)
        cl.font = HEADER_FONT; cl.fill = HEADER_FILL; cl.border = BDR
        cl.alignment = Alignment(wrap_text=True, vertical="center")

def cel(ws, row, col, val, font=None, fill=None):
    c = ws.cell(row=row, column=col, value=val)
    c.font = font or NORMAL; c.border = BDR
    if fill: c.fill = fill
    c.alignment = Alignment(wrap_text=True, vertical="top")
    return c

def set_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

def trunc(items, limit):
    if not items: return ""
    s = ", ".join(str(x) for x in items[:limit])
    if len(items) > limit: s += f"... (+{len(items)-limit} more)"
    return s


def load_categories(folder):
    """Load categories from url_cat.json or similar file."""
    for name in ["url_cat.json", "zia_custom_categories.json", "custom_categories.json"]:
        path = os.path.join(folder, name)
        if os.path.exists(path):
            print(f"  Loading: {name}")
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            cats = data.get("categories", data) if isinstance(data, dict) else data
            print(f"  {len(cats)} categories loaded")
            return cats
    return None


def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(1)

    url_path, ssl_path = sys.argv[1], sys.argv[2]
    folder = os.path.dirname(os.path.abspath(url_path)) or os.getcwd()

    for path in [url_path, ssl_path]:
        try: open(path, "r").close(); print(f"  OK: {path}")
        except Exception as e: print(f"ERROR: {path}: {e}"); sys.exit(1)

    # Load categories
    print("\nStep 1: Loading custom categories...")
    raw_cats = load_categories(folder)
    if not raw_cats:
        print("ERROR: Could not find url_cat.json in the same folder.")
        print("  Place url_cat.json alongside the policy JSONs.")
        sys.exit(1)

    # Load policies
    print("\nStep 2: Loading policies...")
    with open(url_path, "r", encoding="utf-8") as f: url_rules = json.load(f)
    with open(ssl_path, "r", encoding="utf-8") as f: ssl_rules = json.load(f)

    url_usage = defaultdict(list)
    ssl_usage = defaultdict(list)
    std_cats = set()
    for r in url_rules:
        for cat in r.get("urlCategories", []):
            if cat.startswith("CUSTOM_"): url_usage[cat].append(r["name"])
            else: std_cats.add(cat)
    for r in ssl_rules:
        for cat in r.get("urlCategories", []):
            if cat.startswith("CUSTOM_"): ssl_usage[cat].append(r["name"])

    # Build analysis data
    print("\nStep 3: Analyzing...")
    cat_data = []
    for c in sorted(raw_cats, key=lambda x: int(x["id"].replace("CUSTOM_", ""))):
        cid = c["id"]
        urls = c.get("urls", [])
        cat_data.append({
            "id": cid, "name": c.get("name", c.get("configuredName", "")),
            "urls": urls, "url_count": len(urls),
            "url_rules": url_usage.get(cid, []), "ssl_rules": ssl_usage.get(cid, []),
        })

    # URL overlap
    url_to_cats = defaultdict(list)
    for c in cat_data:
        for u in c["urls"]:
            url_to_cats[u].append({"id": c["id"], "name": c["name"]})
    duplicates = {u: cats for u, cats in url_to_cats.items() if len(cats) > 1}

    single_url = [c for c in cat_data if c["url_count"] == 1]
    large = [c for c in cat_data if c["url_count"] > 100]
    unused = [c for c in cat_data if not c["url_rules"] and not c["ssl_rules"]]
    single_rule = [c for c in cat_data if len(c["url_rules"]) + len(c["ssl_rules"]) == 1]
    multi_policy = [c for c in cat_data if c["url_rules"] and c["ssl_rules"]]

    print(f"  Duplicate URLs across categories: {len(duplicates)}")
    print(f"  Single-URL categories: {len(single_url)}")
    print(f"  Large categories (100+): {len(large)}")
    print(f"  Unused: {len(unused)}")
    print(f"  Cross-policy: {len(multi_policy)}")

    # Build Excel
    print("\nStep 4: Building Excel...")
    wb = Workbook()

    # Summary
    ws1 = wb.active; ws1.title = "Analysis Summary"
    ws1["A1"] = "ZIA Custom URL Category — Deep Analysis"
    ws1["A1"].font = TITLE
    r = 3
    for label, val in [
        ("Total custom categories", len(cat_data)),
        ("", ""), ("Hygiene Findings", ""),
        ("URLs in multiple categories", len(duplicates)),
        ("Single-URL categories", len(single_url)),
        ("Large categories (100+ URLs)", len(large)),
        ("Unused (not in any rule)", len(unused)),
        ("Referenced by only 1 rule", len(single_rule)),
        ("Used in both URL + SSL policies", len(multi_policy)),
        ("", ""),
        ("Standard web categories in URL filtering", len(std_cats)),
    ]:
        if label == "Hygiene Findings": ws1.cell(row=r, column=1, value=label).font = SUBTITLE
        elif label:
            ws1.cell(row=r, column=1, value=label).font = NORMAL
            ws1.cell(row=r, column=2, value=val).font = BOLD
        r += 1
    set_widths(ws1, [42, 15])

    # Duplicate URLs
    ws2 = wb.create_sheet("Duplicate URLs")
    ws2["A1"] = f"URLs appearing in multiple categories ({len(duplicates)})"
    ws2["A1"].font = SUBTITLE; ws2.merge_cells("A1:C1")
    hdr(ws2, 2, ["URL / Domain", "# Categories", "Categories"])
    r = 3
    for url, cats in sorted(duplicates.items(), key=lambda x: -len(x[1])):
        cel(ws2, r, 1, url); cel(ws2, r, 2, len(cats))
        cel(ws2, r, 3, ", ".join(f'{c["name"]} ({c["id"]})' for c in cats))
        if len(cats) >= 4: ws2.cell(row=r, column=2).fill = LIGHT_RED
        elif len(cats) >= 3: ws2.cell(row=r, column=2).fill = LIGHT_ORANGE
        r += 1
    ws2.auto_filter.ref = f"A2:C{r-1}"; ws2.freeze_panes = "A3"
    set_widths(ws2, [40, 12, 80])

    # Size Distribution
    ws3 = wb.create_sheet("Size Distribution")
    hdr(ws3, 1, ["#", "Category ID", "Name", "URL Count", "Policy Usage"])
    r = 2
    for i, c in enumerate(sorted(cat_data, key=lambda x: -x["url_count"]), 1):
        cel(ws3, r, 1, i); cel(ws3, r, 2, c["id"]); cel(ws3, r, 3, c["name"]); cel(ws3, r, 4, c["url_count"])
        usage = []
        if c["url_rules"]: usage.append(f"URL ({len(c['url_rules'])})")
        if c["ssl_rules"]: usage.append(f"SSL ({len(c['ssl_rules'])})")
        cel(ws3, r, 5, ", ".join(usage) or "UNUSED", fill=LIGHT_RED if not usage else None)
        if c["url_count"] == 1: ws3.cell(row=r, column=4).fill = LIGHT_YELLOW
        elif c["url_count"] > 100: ws3.cell(row=r, column=4).fill = LIGHT_ORANGE
        r += 1
    ws3.auto_filter.ref = f"A1:E{r-1}"; ws3.freeze_panes = "A2"
    set_widths(ws3, [5, 14, 35, 10, 25])

    # Single URL
    ws4 = wb.create_sheet("Single-URL Categories")
    ws4["A1"] = f"Categories with only 1 URL ({len(single_url)})"
    ws4["A1"].font = SUBTITLE; ws4.merge_cells("A1:D1")
    hdr(ws4, 2, ["Category ID", "Name", "The URL", "Policy Usage"])
    r = 3
    for c in single_url:
        cel(ws4, r, 1, c["id"]); cel(ws4, r, 2, c["name"])
        cel(ws4, r, 3, c["urls"][0] if c["urls"] else "")
        usage = trunc(c["url_rules"] + c["ssl_rules"], 3)
        cel(ws4, r, 4, usage or "UNUSED", fill=LIGHT_RED if not usage else None)
        r += 1
    set_widths(ws4, [14, 30, 40, 40]); ws4.freeze_panes = "A3"

    # Unused
    ws5 = wb.create_sheet("Unused Categories")
    ws5["A1"] = f"Not referenced by any rule ({len(unused)})"
    ws5["A1"].font = SUBTITLE; ws5.merge_cells("A1:D1")
    hdr(ws5, 2, ["Category ID", "Name", "URL Count", "URLs"])
    r = 3
    for c in unused:
        cel(ws5, r, 1, c["id"]); cel(ws5, r, 2, c["name"])
        cel(ws5, r, 3, c["url_count"]); cel(ws5, r, 4, trunc(c["urls"], 10))
        r += 1
    set_widths(ws5, [14, 35, 10, 60]); ws5.freeze_panes = "A3"

    # Cross-Policy
    ws6 = wb.create_sheet("Cross-Policy Usage")
    ws6["A1"] = f"Used in both URL filtering and SSL ({len(multi_policy)})"
    ws6["A1"].font = SUBTITLE; ws6.merge_cells("A1:E1")
    hdr(ws6, 2, ["Category ID", "Name", "URL Filtering Rules", "SSL Rules", "Potential Issue"])
    r = 3
    for c in multi_policy:
        cel(ws6, r, 1, c["id"]); cel(ws6, r, 2, c["name"])
        cel(ws6, r, 3, ", ".join(c["url_rules"])); cel(ws6, r, 4, ", ".join(c["ssl_rules"]))
        url_n = " ".join(c["url_rules"]).lower()
        ssl_n = " ".join(c["ssl_rules"]).lower()
        cat_words = [w for w in c["name"].lower().replace("_", " ").split() if len(w) > 3]
        url_has = any(w in url_n for w in cat_words) if cat_words else True
        ssl_has = any(w in ssl_n for w in cat_words) if cat_words else True
        if not url_has or not ssl_has:
            cel(ws6, r, 5, "Review — rule names suggest different services", fill=LIGHT_RED)
        else: cel(ws6, r, 5, "")
        ws6.row_dimensions[r].height = 30; r += 1
    set_widths(ws6, [14, 30, 40, 45, 40]); ws6.freeze_panes = "A3"

    # Standard
    ws7 = wb.create_sheet("Standard Web Categories")
    ws7["A1"] = f"Predefined ZIA categories in URL filtering ({len(std_cats)})"
    ws7["A1"].font = SUBTITLE; ws7.merge_cells("A1:B1")
    hdr(ws7, 2, ["#", "Category Name"])
    for i, cat in enumerate(sorted(std_cats), 1):
        cel(ws7, i + 2, 1, i); cel(ws7, i + 2, 2, cat)
    set_widths(ws7, [6, 45])

    xlsx = os.path.join(os.getcwd(), "ZIA_WebCategory_Analysis.xlsx")
    wb.save(xlsx); print(f"  Saved: {xlsx}")

    # Word doc
    if HAS_DOCX:
        print("\nStep 5: Building Word doc...")
        doc = DocxDocument()
        style = doc.styles["Normal"]; style.font.name = "Calibri"; style.font.size = Pt(11)
        style.paragraph_format.space_after = Pt(6)

        doc.add_heading("ZIA Custom URL Category Analysis", level=0)
        doc.add_paragraph("Network Security Engineering — Security Control Management")

        doc.add_heading("Summary", level=1)
        doc.add_paragraph(
            f"Analysis of {len(cat_data)} custom URL categories identified hygiene issues "
            f"that should be addressed to improve accuracy and manageability."
        )

        doc.add_heading("Duplicate URLs Across Categories", level=1)
        max_dup = max(len(v) for v in duplicates.values()) if duplicates else 0
        doc.add_paragraph(
            f"{len(duplicates)} URLs appear in multiple categories (up to {max_dup} categories). "
            f"This creates ambiguity about which category controls access and can cause unexpected "
            f"behavior when categories are used in different rules with different actions."
        )

        doc.add_heading("Single-URL Categories", level=1)
        doc.add_paragraph(
            f"{len(single_url)} categories contain only one URL. Some serve a purpose (per-user SSL "
            f"bypass), others may consolidate into broader categories."
        )

        doc.add_heading("Large Categories", level=1)
        doc.add_paragraph(f"{len(large)} categories have 100+ URLs. The largest:")
        for c in sorted(cat_data, key=lambda x: -x["url_count"])[:5]:
            doc.add_paragraph(f'{c["name"]}: {c["url_count"]} URLs', style="List Bullet")

        doc.add_heading("Unused Categories", level=1)
        doc.add_paragraph(
            f"{len(unused)} categories are not referenced by any rule. "
            f"Candidates for deletion or may indicate orphaned categories from removed rules."
        )

        doc.add_heading("Cross-Policy Consistency", level=1)
        doc.add_paragraph(
            f"{len(multi_policy)} categories are shared between URL filtering and SSL inspection. "
            f"When a category is used in both, the URL list affects both access control and SSL bypass. "
            f"Categories where rule names reference different services may indicate misconfiguration."
        )

        doc.add_heading("Recommendations", level=1)
        recs = [
            f"Audit the {len(duplicates)} duplicate URLs, starting with those in 4+ categories.",
            f"Review {len(single_url)} single-URL categories for consolidation.",
            f"Delete or archive {len(unused)} unused categories after confirming not pending deployment.",
            "Audit the largest categories (SSL bypass, Server/User Allowed Sites) for stale entries.",
            "Resolve cross-policy mismatches where different services share a category.",
        ]
        for rec in recs:
            doc.add_paragraph(rec, style="List Bullet")

        docx = os.path.join(os.getcwd(), "ZIA_WebCategory_Analysis.docx")
        doc.save(docx); print(f"  Saved: {docx}")

    print("\nDone!")

if __name__ == "__main__":
    main()
